LDAP_HOST: ldap.thoughtworks.io
LDAP_PORT: 389
LDAP_USER: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31323165313766366661376161303163343138343336646661333432303833343362643531313130
          3939386432613033336562386530636161373062316239650a653532656134656337323739326234
          38333538616433393831626131386439383866643838343037303637633339353538323965393061
          3539643565363037630a376337656632386265653031303333393563643333316133633130383333
          3233
LDAP_BIND_DN: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63386565623065613433333130313230356437383432623237386262343464333530346531663236
          3162356537393130353363636437636261343134316536350a656231366363356163373265633233
          61343837393230653936363831346165616533353561316661616161656363393462623239306465
          6363343834303236610a623433623565616130396339313637363261356265356261613233626263
          38653637346536653066343037343061366462663132653331373631653231623661653162633763
          66343330613766623765373861616130356232613636303432666639373336643166333338633239
          30623265383262333338646435303036633735356564346130313637616434366631326233616232
          33333238346265343165633630663031633230343131613461613465306532306265623062336332
          31623361656132326635343064336532353238313661613064346430353862623962
LDAP_BIND_PASS: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31336133353230646462616238343566646265616563323138646361663232633630353136313037
          6433373634663063363836636366336632393436353865330a386433363161623335316335646135
          63373561623861373432623166646666643565353464356334343230343763363537643462623939
          3862626631613236610a343237346465663637303637333261663830333134373665363865386130
          31303238336236636464613130353632353464336433346263656562333134383038
LDAP_BIND_ENCRYPT: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65353061303534306231616238623766363464383765396164616365393763323761356130306338
          3636313038663831363939663832363638363435383961650a323039663536656330646532383263
          62343338626233386337343163383737626166643366323136376233306561663363643037393763
          6330386236393563320a343266653435316465666237393339353638396533656136376239343835
          31366437626133663764616237666362316433343561356537633566306636326265363864356661
          3030376562376135376239353438326330306538336465653531
LDAP_DOMAIN: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31386237356433386635366166656264643633616139356561343662333134646436656566383032
          3663393331336463386239383434353065303339373662300a333365353035643737396532616537
          35336238326161303637376531353134346435353334616338363263393837353632666639326634
          3736373836343361650a383165633166323539326637636530313861653661646133643363336361
          36656263393335613030376237613766326239633435636436623038313935643034
LDAP_BASE_DN: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62666534373165323239383130373839396433386637383839653431653936336230626333663063
          3537396164346638613961323861393639623331356537300a626633656565633935633961653763
          62303564316266656236633063313331356336363361363039396430643234343362613634613964
          3031356230396461640a386465313939666163383965666637333663323136313862663361363931
          64356661323637363334666632366664393662663730623161656236636162333438646362323235
          38316531616565613163303766353936643838343539323839313532643539343931346364663731
          303139356163373466393738313139333534
LDAP_USER_SEARCH_BASE: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35633535633963616137363064646434363266633532306464346434623533353561613531613864
          6537333335623962366430623731653836633932393736300a333737666463656238383563363535
          33663030363666373666613563623263386336623564626136306637336365306666373239623036
          3264616434343038660a323932343737323037336463663637346166626535643162656435306631
          3831
LDAP_USER_SEARCH_FILTER: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30353361323361383264636232343066663064636530396434363134313532613066303630643937
          6266366266623762626233386261643335373362306537320a316262643733336533623062633363
          33373937306438373962613361303430343134356164323538616266643238663638383263383732
          6539663037316337300a316238323666633935363837353765316162373435396430303639623337
          31613832393461353234643364336535346262396132653234333466376365383665
LDAP_GROUP_SEARCH_BASE: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34353865633134393738306133636334313439376137396565633536643834396538646662383465
          3931653731656633623832343239613736613839343864660a306361346436323365363064303035
          35353633346532636230346565383238616261373161336363333061356266326262663565643739
          3734623934656466310a316363653330336335356265643937376237626632303030636637656565
          3239
LDAP_HROUP_SEARCH_FILTER: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64376238643335366138396333343437356365383332613931623035396336653263353164356461
          3638333266366530633333363663323364393738373333380a376564623039326163336437616465
          61633264333334386132333066316434616565646635613337373032303865393933633831313261
          6166366339646361630a373662633466396330633030323235313430316665336332313166646538
          39356566306665633336646237333731353963363438336564316234303035396461633332613030
          3332663536623137633464313064346633323831646634613563
