---
- name: create nexus data directory
  file:
    path: "{{ nexus_data_dir }}"
    state: "directory"
    owner: 200
    group: root
  become: yes

- name: check nexus data directory
  command: "ls {{ nexus_data_dir }}"
  register: nexus_data_dir_contents
  become: yes

- name: start nexus server container
  docker_container:
    name: "{{ nexus_name }}"
    image: "{{ nexus_image }}:{{ nexus_version }}"
    ports:
      - "{{ nexus_port }}:8081"
      - 5000:5000
      - 5001:5001
      - 5002:5002
    volumes:
      - "{{ nexus_data_dir }}:/nexus-data"
    restart_policy: always
  become: yes

- name: wait for nexus server to be ready...
  wait_for:
    port: "{{ nexus_port }}"
    delay: 5

- name: remove nexus server groovy script
  uri:
    url: "http://localhost:{{ nexus_port }}/service/siesta/rest/v1/script/{{ item }}"
    method: DELETE
    user: "{{ nexus_admin_user }}"
    password: "{{ nexus_admin_pass }}"
    force_basic_auth: yes
    status_code: 204,404
  with_items:
    - initialize
    - privileges
    - roles
    - users
    - repositories

- name: publish nexus server groovy script
  uri:
    url: "http://localhost:{{ nexus_port }}/service/siesta/rest/v1/script"
    method: POST
    user: "{{ nexus_admin_user }}"
    password: "{{ nexus_admin_pass }}"
    force_basic_auth: yes
    body:
      name: "{{ item }}"
      type: "groovy"
      content: "{{ lookup('file', 'groovy/' + item + '.groovy') }}"
    body_format: json
    status_code: 204
  with_items:
    - initialize
    - privileges
    - roles
    - users
    - repositories

- name: initialize nexus environment
  uri:
    url: "http://localhost:{{ nexus_port }}/service/siesta/rest/v1/script/initialize/run"
    method: POST
    user: "{{ nexus_admin_user }}"
    password: "{{ nexus_admin_pass }}"
    force_basic_auth: yes
    headers:
      Content-Type: "text/plain"
    status_code: 200,204
  when: nexus_data_dir_contents.stdout == ""
